# Generated by Django 4.2.4 on 2023-08-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
