# Generated by Django 4.2.4 on 2023-08-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.CharField(choices=[('on', '1'), ('tw', '2'), ('th', '3'), ('fo', '4'), ('fi', '5')], default='fi', max_length=2),
        ),
    ]
