# Generated by Django 4.2.4 on 2023-08-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_review_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.CharField(choices=[('(1/5)', '1'), ('(2/5)', '2'), ('(3/5)', '3'), ('(4/5)', '4'), ('(5/5)', '5')], default='(5/5)', max_length=10),
        ),
    ]
