# Generated by Django 4.2.4 on 2023-08-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_remove_info_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
