# Generated by Django 4.2.4 on 2023-08-11 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_alter_image_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Photo',
        ),
    ]
