# Generated by Django 4.2.4 on 2023-08-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_rename_image_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='voter',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
