# Generated by Django 4.2.4 on 2023-08-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_info_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='voter',
            field=models.IntegerField(),
        ),
    ]
