# Generated by Django 4.2.4 on 2023-08-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_info_author_remove_info_voter_info_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='restother',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='restpeople',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='restplace',
            field=models.CharField(choices=[('실내 쉼터', '실내 쉼터'), ('실외 쉼터', '실외 쉼터')], default='실내 쉼터', max_length=20),
        ),
    ]
