# Generated by Django 4.2.4 on 2023-08-14 01:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0011_info_restother_info_restpeople_info_restplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='voter',
            field=models.ManyToManyField(null=True, related_name='voter_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
