# Generated by Django 4.2.4 on 2023-08-14 01:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0012_alter_info_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='voter',
            field=models.ManyToManyField(blank=True, null=True, related_name='voter_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
